version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=devdb
      - MYSQL_ROOT_PASSWORD=devpassword
    ports:
      - '3306:3306'
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  ftvsr:
    build: 
      context: ../ai/ftvsr
      dockerfile: Dockerfile
    ports:
      - '5000:80'

volumes:
  db:
    driver: local
